# Generated by Django 4.2.28 on 2026-02-14 17:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MapProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_station', models.PositiveIntegerField(default=1)),
                ('completed_stations', models.JSONField(blank=True, default=list)),
                ('completed_super_stations', models.JSONField(blank=True, default=list)),
                ('points', models.PositiveIntegerField(default=0)),
                ('correct_answers', models.PositiveIntegerField(default=0)),
                ('achievements', models.JSONField(blank=True, default=list)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='map_progress', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'התקדמות מפה',
                'verbose_name_plural': 'התקדמות מפה',
            },
        ),
    ]
